# Generated by Django 5.2.4 on 2025-08-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
