# Generated by Django 5.2.4 on 2025-08-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_alter_movie_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.CharField(max_length=1000),
        ),
    ]
