# Generated by Django 5.2.4 on 2025-08-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_alter_movie_title_alter_review_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(max_length=2500),
        ),
    ]
